home/urls.py
from django.urls import path
from .views import home, contact, service, about, download

app_name = "home"
urlpatterns = [
    path('', home, name="home"),
    path('about/', about, name="about"),
    path('contact/', contact, name="contact"),
    path('services/', service, name="service"),
    path('downloads/', download, name="download"),
]

home/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
DOWNLOAD_FILE_TYPE_CHOICES = [
    ('pdf', 'PDF'),
    ('img', 'Image'),
    ('edt', 'Editable Document'),
    ('sht', 'Sheet'),
    ('oth', 'Other'),
]


class About(models.Model):
    about_short = models.TextField("About Short Content")
    about_long = RichTextUploadingField("About Long Content", default=None)

    def __str__(self):
        return self.about_short


class Contact(models.Model):
    company_name = models.CharField("Company Name", max_length=100)
    logo = models.ImageField(upload_to='contact/', default='logo.png')
    phone_number = models.CharField(
        "Land Line Number", max_length=10, blank=True, null=True)
    phone_number2 = models.CharField(
        "Next Land Line Number", max_length=10, blank=True, null=True)
    mobile_number = models.CharField(
        "Mobile Number", max_length=10, blank=True, null=True)
    email = models.EmailField("Email", max_length=254)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.company_name


class ContactForm(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    address = models.CharField(max_length=250, blank=True, null=True)
    phone_number = models.CharField(max_length=10, blank=True, null=True)
    message = models.TextField()
    timestamp = models.DateTimeField(
        "Contact Date", auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.full_name

    class Meta:
        ordering = ["-timestamp"]
        verbose_name = "Contact Us Form"
        verbose_name_plural = "Contact Us Form"


class Social(models.Model):
    facebook = models.URLField("Facebook Page", max_length=200)
    twitter = models.URLField("Twitter", max_length=200)
    youtube = models.URLField("Youtube Channel", max_length=200)

    def __str__(self):
        return self.facebook


class Review(models.Model):
    name = models.CharField("Full Name", max_length=50)
    heading = models.CharField(max_length=26)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)
    avatar = models.ImageField("Profile Photo", upload_to='reviews/',
                               height_field=None, width_field=None, max_length=None)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class NewsLetter(models.Model):
    email = models.EmailField(max_length=254)
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.email


class Service(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(
        "Image", upload_to='services/', blank=True, null=True, default=None)
    icon = models.CharField(blank=True, null=True,
                            max_length=100, help_text="Get relevent icons from https://fontawesome.com/v4.7.0/icons/")

    def __str__(self):
        return self.title


class Download(models.Model):
    file_name = models.CharField("File Name", max_length=250)
    file = models.FileField("File", upload_to='downloads/')
    file_type = models.CharField("File Type",
                                 choices=DOWNLOAD_FILE_TYPE_CHOICES, default='pdf', max_length=3)
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.file_name

    def get_file_type(self):
        if self.file_type == 'pdf':
            return 'PDF'
        elif self.file_type == 'img':
            return 'Image'
        elif self.file_type == 'edt':
            return 'Editable Document'
        elif self.file_type == 'sht':
            return 'Spread Sheet'
        else:
            return 'Other'


class HomeSlider(models.Model):
    caption = models.CharField(max_length=150)
    sub_caption = models.CharField(max_length=400)
    image = models.ImageField(upload_to='sliders/')

    def __str__(self):
        return self.caption

home/forms.py
from django import forms
from .models import NewsLetter, ContactForm


class NewsLetterForm(forms.ModelForm):
    class Meta:
        model = NewsLetter
        fields = ["email"]


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactForm
        fields = [
            "full_name",
            "email",
            "phone_number",
            "address",
            "message"
        ]

home/views.py
from django.shortcuts import render
from .models import Review, Download, About, Service, HomeSlider
from article.models import News, Notice
from .forms import ContactUsForm
from django.contrib import messages


def home(request):
    review_list = Review.objects.all()
    slider = HomeSlider.objects.all()
    service_list = Service.objects.all()
    latest_news = News.objects.filter(draft=False).order_by("-date")
    flash_notice = Notice.objects.filter(flash_notice=True)
    flash_notice_exists = flash_notice.exists()
    context = {
        "review_list": review_list,
        "latest_news": latest_news and latest_news[0:2],
        "flash_notice": flash_notice and flash_notice[0],
        "flash_notice_exists": flash_notice_exists,
        "service_list": service_list,
        "slider": slider,
        "home": True
    }
    return render(request, 'home/index.html', context)


def about(request):
    context = {
        "about_active": True
    }
    return render(request, 'home/about.html', context)


def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Your message have been successfully recieved.')
        else:
            messages.error(
                request, 'Error submitting your message! Please correct errors and Try again.')
    context = {"contact_active": True}
    return render(request, 'home/contact.html', context)


def service(request):
    service_list = Service.objects.all()
    context = {
        "service_list": service_list,
        "service": True
    }
    return render(request, 'home/services.html', context)


def download(request):
    download_list = Download.objects.all()
    context = {
        "download_list": download_list,
        "download": True
    }
    return render(request, 'home/downloads.html', context)

templates/home/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta_links %}
{% endblock %}
{% block style_links %}

{% endblock %}

{% block title %}
Home
{% endblock %}
{% block content %}
<div class="page-top">
    <div class="container page-heading" style="margin-top:180px;">
        <div class="row">
            <div class="col">
                <h1 class="text-center">About Us</h1>
            </div>
        </div>
    </div>
</div>
<div class="page-content js-animated" data-animate data-animation-classes="animated fadeInUp slow">
    <div class="container">
        <div class="row">
            <div class="col">
                <div>{{about.about_long|safe}}</div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script_links %}
{% endblock %}
{% block scripts %}

{% endblock %}

templates/home/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta_links %}
{% endblock %}
{% block style_links %}

{% endblock %}

{% block title %}
Home
{% endblock %}
{% block content %}
<div class="page-top">
    <div class="container page-heading" style="margin-top:180px;">
        <div class="row">
            <div class="col">
                <h1 class="text-center">Contact us</h1>
            </div>
        </div>
    </div>
</div>
<div class="page-content js-animated" style="margin-top: 100px;" data-animate
    data-animation-classes="animated fadeInUp slow">
    <div id="map"></div>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 col-xs-12 mb-4">
                <div class="contact__wrapper">
                    <h2>{{contact.company_name}}</h2>
                    <p><span class="fa fa-phone mr-2"></span>{{contact.phone_number}}, {{contact.phone_number2}},
                        {{contact.mobile_number}} </p>
                    <p><span class="fa fa-envelope mr-2"></span>{{contact.email}}</p>
                    <p><span class="fa fa-map-marker mr-2"></span> <span>{{contact.address}}</span></p>
                </div>
            </div>
            <div class="col-md-6 col-xs-12">
                <h2 class="text-center">Get in touch</h2>
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <input required type="text" class="form-control" name="full_name" id="id_full_name"
                            placeholder="Full Name*">
                    </div>
                    <div class="form-group">
                        <input required type="email" class="form-control" name="email" id="id_email"
                            placeholder="Email*">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="phone_number" id="id_phone_number"
                            placeholder="Phone Number">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="address" id="id_address" placeholder="Address">
                    </div>
                    <div class="form-group">
                        <textarea required name="message" class="form-control" placeholder="Your message*"
                            id="id_message" cols="30" rows="10"></textarea>
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-primary my-3" role="alert">
                    {{message}}
                </div>
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script_links %}
<!-- <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDIJ9XX2ZvRKCJcFRrl-lRanEtFUow4piM&callback=initMap"
    type="text/javascript"></script> -->
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAUdBmratEzJjKO6eueiRneuqYqzco3mdg&callback=initMap"
    type="text/javascript"></script>
{% endblock %}
{% block scripts %}
<script>
    var map;

    function initMap() {
        var myLatLng = {
            lat: 27.700924,
            lng: 85.322938
        };
        map = new google.maps.Map(document.getElementById('map'), {
            center: myLatLng,
            zoom: 16
        });
        var marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            title: 'Premier Securities'
        });
    }
</script>
{% endblock %}

templates/home/downloads.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta_links %}
{% endblock %}
{% block style_links %}

{% endblock %}

{% block title %}
Downloads
{% endblock %}
{% block content %}
<div class="page-top">
    <div class="container page-heading" style="margin-top:180px;">
        <div class="row">
            <div class="col">
                <h1 class="text-center">Downloads</h1>
            </div>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="container">
        <div class="row">
            {% if not download_list %}
            <div class="col">
                <p>No download content found.</p>
            </div>
            {% else %}
            <div class="col">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>SN</th>
                            <th>File Name</th>
                            <th>Document Type</th>
                            <th>Uploaded Date</th>
                            <!-- <th>Action</th> -->
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in download_list %}
                        <tr>
                            <td>{{forloop.counter}}.</td>
                            <td><a href="{{item.file.url}}"><i class="fa fa-download mr-1"></i> {{item.file_name}}</a>
                            </td>
                            <td>{{item.get_file_type}}</td>
                            <td>{{item.timestamp}}</td>
                            <!-- <td><a href="{{item.file.url}}" class="btn btn-primary btn-sm">Download</a></td> -->
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}

    </div>
</div>
{% endblock %}

{% block script_links %}
{% endblock %}
{% block scripts %}

{% endblock %}

templates/home/services.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta_links %}
{% endblock %}
{% block style_links %}

{% endblock %}

{% block title %}
Services
{% endblock %}
{% block content %}
<div class="page-top">
    <div class="container page-heading" style="margin-top:180px;">
        <div class="row">
            <div class="col">
                <h1 class="text-center">Services</h1>
            </div>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="container">
            <div class="row mb-5">
                <div class="col">
                    <p class="text-center">Improve your trading skills by using our extensive services. We are always here to guide you in every step.</p>
                </div>
            </div>
        <div class="row">
            {% for service in service_list %}
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="service-block mb20 pinside30 outline text-center">
                    <div class="service-icon mb30">
                        {% if service.image %}<img src="{{service.image.url}}" class="img-responsive"
                            alt="{{service.title}}"> {% else %} <i class="{{service.icon}}"
                            style="font-size: 5rem;"></i> {% endif %}
                    </div>
                    <div class="">
                        <h2 class="heading-title">{{service.title}}</h2>
                        <p>{{service.content}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block script_links %}
{% endblock %}
{% block scripts %}

{% endblock %}