article/urls.py
from django.urls import path
from article.views import article, article_detail, notice, tag_article, notice_detail

app_name = "article"

urlpatterns = [
    path('', article, name="articles"),
    path('notices/', notice, name="notices"),
    path('<slug:slug>', article_detail, name="articleDetail"),
    path('notice/<slug:slug>', notice_detail, name="noticeDetail"),
    path('tag/<str:name>', tag_article, name="tagNews")

]

home/urls.py
from django.urls import path
from .views import home, contact, service, about, download

app_name = "home"
urlpatterns = [
    path('', home, name="home"),
    path('about/', about, name="about"),
    path('contact/', contact, name="contact"),
    path('services/', service, name="service"),
    path('downloads/', download, name="download"),
]

home/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
DOWNLOAD_FILE_TYPE_CHOICES = [
    ('pdf', 'PDF'),
    ('img', 'Image'),
    ('edt', 'Editable Document'),
    ('sht', 'Sheet'),
    ('oth', 'Other'),
]


class About(models.Model):
    about_short = models.TextField("About Short Content")
    about_long = RichTextUploadingField("About Long Content", default=None)

    def __str__(self):
        return self.about_short


class Contact(models.Model):
    company_name = models.CharField("Company Name", max_length=100)
    logo = models.ImageField(upload_to='contact/', default='logo.png')
    phone_number = models.CharField(
        "Land Line Number", max_length=10, blank=True, null=True)
    phone_number2 = models.CharField(
        "Next Land Line Number", max_length=10, blank=True, null=True)
    mobile_number = models.CharField(
        "Mobile Number", max_length=10, blank=True, null=True)
    email = models.EmailField("Email", max_length=254)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.company_name


class ContactForm(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    address = models.CharField(max_length=250, blank=True, null=True)
    phone_number = models.CharField(max_length=10, blank=True, null=True)
    message = models.TextField()
    timestamp = models.DateTimeField(
        "Contact Date", auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.full_name

    class Meta:
        ordering = ["-timestamp"]
        verbose_name = "Contact Us Form"
        verbose_name_plural = "Contact Us Form"


class Social(models.Model):
    facebook = models.URLField("Facebook Page", max_length=200)
    twitter = models.URLField("Twitter", max_length=200)
    youtube = models.URLField("Youtube Channel", max_length=200)

    def __str__(self):
        return self.facebook


class Review(models.Model):
    name = models.CharField("Full Name", max_length=50)
    heading = models.CharField(max_length=26)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)
    avatar = models.ImageField("Profile Photo", upload_to='reviews/',
                               height_field=None, width_field=None, max_length=None)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class NewsLetter(models.Model):
    email = models.EmailField(max_length=254)
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.email


class Service(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(
        "Image", upload_to='services/', blank=True, null=True, default=None)
    icon = models.CharField(blank=True, null=True,
                            max_length=100, help_text="Get relevent icons from https://fontawesome.com/v4.7.0/icons/")

    def __str__(self):
        return self.title


class Download(models.Model):
    file_name = models.CharField("File Name", max_length=250)
    file = models.FileField("File", upload_to='downloads/')
    file_type = models.CharField("File Type",
                                 choices=DOWNLOAD_FILE_TYPE_CHOICES, default='pdf', max_length=3)
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.file_name

    def get_file_type(self):
        if self.file_type == 'pdf':
            return 'PDF'
        elif self.file_type == 'img':
            return 'Image'
        elif self.file_type == 'edt':
            return 'Editable Document'
        elif self.file_type == 'sht':
            return 'Spread Sheet'
        else:
            return 'Other'


class HomeSlider(models.Model):
    caption = models.CharField(max_length=150)
    sub_caption = models.CharField(max_length=400)
    image = models.ImageField(upload_to='sliders/')

    def __str__(self):
        return self.caption

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="Premire Securites - description ">
    <meta name="keywords" content="stock broker, nepse, Premire Securites">
    {% block meta_links %}
    {% endblock %}
    <link rel=shortcut icon type=image/png href="{% static 'favicon.ico' %}">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- font css -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animsition.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
    <link rel="stylesheet" href="{% static 'css/base_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block style_links %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class="top-header d-none d-md-block">
        <!-- top heder -->
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="pull-right">
                        <span class="top-link"><i class="fa fa-phone"></i> {{contact.phone_number}}</span>
                        <span class="top-link"><i class="fa fa-envelope"></i> {{contact.email}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.top header -->
    <!-- navigation-transparent -->
    <div class="header">
        <!-- navigation -->
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 text-center">
                    <p class="text-uppercase" style="color:white; font-size: 20px; margin-bottom: 0px;"><strong>Trust of Investors</strong></p>
                    <a class="logo" href="/"><img src="{{contact.logo.url}}" alt="" style="width: 70%;"></a>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div id="navigation" class="navigation">
                        <ul class="pull-right">
                            <li class=" navigation-link {% if home %} active {% endif %}"><a href="/"
                                    class="animsition-link">Home</a>
                            </li>
                            <li class="navigation-link {% if about_active %} active {% endif %}"><a
                                    href="{% url 'home:about' %}" class="animsition-link">About</a>
                            <li class="navigation-link {% if service %}active {% endif %}"><a
                                    href="{% url 'home:service' %}" class="animsition-link">Services</a>
                            </li>
                            <li class="navigation-link {% if download %} active {% endif %}"><a
                                    href="{% url 'home:download' %}" class="animsition-link">Downloads</a>
                            <li class="navigation-link {% if news %} active {% endif %}"><a href="#"
                                    class="animsition-link">News</a>
                                <ul>
                                    <li><a href="{% url 'article:articles' %}" class="animsition-link">News
                                            and Articles</a>
                                    </li>
                                    <li><a href="{% url 'article:notices' %}" class="animsition-link">Notices</a></li>
                                </ul>
                            </li>
                            <li class="navigation-link {% if contact_active %} active {% endif %}"><a
                                    href="{% url 'home:contact' %}" class="animsition-link">Contact</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.navigation -->
    {% block content %}
    {% endblock %}

    <div class="footer section-space60">
        <!-- footer -->
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <div class="footer-widget mb20">
                        <!-- footer-widget -->
                        <h3 class="footer-title">Contact Info</h3>
                        <div class="ft-contact-info">
                            <!-- ft contact info -->
                            <div class="ft-icon">
                                <!-- ft icon -->
                                <i class="fa fa-phone"></i>
                            </div>
                            <!-- /.ft icon -->
                            <div class="ft-content">
                                <!-- ft content -->
                                {{contact.phone_number}} {% if contact.phone_number2 %},
                                {{contact.phone_number2}}{% endif %}
                            </div>
                            <!-- /.ft content -->
                        </div>
                        <!-- /.ft contact info -->
                        <div class="ft-contact-info">
                            <!-- ft contact info -->
                            <div class="ft-icon">
                                <!-- ft icon -->
                                <i class="fa fa-envelope"></i>
                            </div>
                            <!-- /.ft icon -->
                            <div class="ft-content">
                                <!-- ft content -->
                                {{contact.email}}
                            </div>
                            <!-- /.ft content -->
                        </div>
                        <!-- /.ft contact info -->
                        <div class="ft-contact-info">
                            <!-- ft contact info -->
                            <div class="ft-icon">
                                <!-- ft icon -->
                                <i class="fa fa-map-marker"></i>
                            </div>
                            <!-- /.ft icon -->
                            <div class="ft-content">
                                <!-- ft content -->
                                {{contact.address}}
                            </div>
                            <!-- /.ft content -->
                        </div>
                        <!-- /.ft contact info -->
                    </div>
                    <!-- /.footer-widget -->
                </div>
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-12">
                    <div class="footer-widget mb20">
                        <!-- footer-widget -->
                        <h3 class="footer-title">Quick Links</h3>
                        <ul class="bullet listnone no-padding mb0">
                            <li><i class="fa fa-angle-right"></i> <a href="/" class="Home">Home</a></li>
                            <li><i class="fa fa-angle-right"></i> <a href="{% url 'home:about' %}"
                                    title="Services">About</a></li>
                            <li><i class="fa fa-angle-right"></i> <a href="{% url 'home:service' %}"
                                    title="Blog">Services</a></li>
                            <li><i class="fa fa-angle-right"></i> <a href="{% url 'home:download' %}"
                                    title="Blog">Downloads</a></li>
                            <li><i class="fa fa-angle-right"></i> <a href="{% url 'home:contact' %}"
                                    title="Contact us">Contact
                                    us</a></li>
                        </ul>
                        <!-- /.footer-widget -->
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <div class="footer-widget mb20">
                        <!-- footer-widget -->
                        <h3 class="footer-title">Follow Us On</h3>
                        <ul class="listnone no-padding mb0">
                            {% if social.facebook %}<li class="footer-link"><a href="{{social.facebook}}"
                                    target="_blank"><i class="fa fa-facebook-square "></i> facebook</a>{% endif %}

                            </li>
                            {% if social.twitter %}<li class="footer-link"><a href="{{social.twitter}}"
                                    target="_blank"><i class="fa fa-twitter-square "></i> twitter</a>{% endif %}
                            </li>
                            {% if social.youtube %}<li class="footer-link"><a href="{{social.youtube}}"
                                    target="_blank"><i class="fa fa-youtube-play "></i>
                                    Youtube</a></li>{% endif %}
                        </ul>
                    </div>
                    <!-- /.footer-widget -->
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="footer-widget">
                        <!-- footer-widget -->
                        <h3 class="footer-title">Newsletter</h3>
                        <p>Subscribe our email newsletter today to receive updates.</p>
                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="id_email" class="sr-only control-label">Email</label>
                                <input type="email" name="email" class="form-control" id="id_email"
                                    placeholder="Enter Email Address">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline">Subscribe</button>
                            </div>
                        </form>
                        {% if messages %}
                        {% for message in messages %}
                        <p>
                            {{message}}
                        </p>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <!-- /.footer-widget -->
                </div>
            </div>
        </div>
    </div>
    <!-- /.footer -->
    <div class="tiny-footer">
        <!-- tiny-footer -->
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <p class="text-center text-md-left">© {{contact.company_name}}, <span id="date"></span>. All
                        Rights Reserved.</p>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <p class="text-center text-md-right">Powered
                        by <a href="https://techkunja.com.np">Tech Kunja</a></p>
                </div>
            </div>
        </div>
    </div>
    <!-- /.tiny-footer -->
    <!-- back to top icon -->
    <a href="#0" class="cd-top" title="Go to top">Top</a>


    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="{% static 'js/menumaker.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.sticky.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/animate.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/animsition.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/sticky-header.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    {% block script_links %}
    {% endblock %}
    <script type="text/javascript">
        $('#date').text(new Date().getFullYear())
        $("#navigation").menumaker({
            title: "Menu",
            format: "multitoggle"
        });
    </script>
    {% block scripts %}
    {% endblock %}
</body>

</html>